Web/AuctionHouse.Web/Areas/Administration/Controllers/UserController.cs
namespace AuctionHouse.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using AuctionHouse.Services.Data;
    using AuctionHouse.Web.ViewModels.Users;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Area("Administration")]
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index(int id = 1)
        {
            const int ItemsPerPage = 8;

            if (id <= 0)
            {
                return this.NotFound();
            }

            var viewModel = new ListUsersViewModel()
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                Users = await this.userService.GetAllAsync(id, ItemsPerPage),
                Count = this.userService.UsersCount(),
            };

            return this.View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult SingleUser(string userId)
        {
            if (userId == string.Empty)
            {
                return this.NotFound();
            }

            var user = this.userService.GetUser(userId);

            return this.View(user);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SingleUser(string userId, decimal balance)
        {
            if (userId == string.Empty)
            {
                return this.NotFound();
            }

            await this.userService.AddMoneyAsync(userId, balance);

            return this.RedirectToAction("Index");
        }
    }
}

Web/AuctionHouse.Web/Controllers/AuctionsController.cs
namespace AuctionHouse.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using AuctionHouse.Data.Common.Repositories;
    using AuctionHouse.Data.Models;
    using AuctionHouse.Services.Data;
    using AuctionHouse.Web.Hubs;
    using AuctionHouse.Web.ViewModels.Auctions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.SignalR;

    public class AuctionsController : Controller
    {
        private readonly ICategoriesService categoriesService;
        private readonly IAuctionService auctionService;
        private readonly IWebHostEnvironment environment;
        private readonly IUserService userService;
        private readonly IBidsService bidsService;

        private readonly int[] bids = new[] { 10, 20, 50, 100, 200, 300, 500, 1000, 3000, 5000 };

        private readonly IRepository<History> historiesRepository;

        public AuctionsController(
            ICategoriesService categoriesService,
            IAuctionService auctionService,
            IWebHostEnvironment environment,
            IUserService userService,
            IBidsService bidsService,
            IRepository<History> historiesRepository)
        {
            this.categoriesService = categoriesService;
            this.auctionService = auctionService;
            this.environment = environment;
            this.userService = userService;
            this.bidsService = bidsService;
            this.historiesRepository = historiesRepository;
        }

        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new CreateAuctionInputModel();
            viewModel.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateAuctionInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            try
            {
                await this.auctionService.CreateAsync(input, userId, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);

                input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();
                return this.View(input);
            }

            this.TempData["Message"] = "The auction was successfully created and is waiting for the admin's approval.";

            return this.RedirectToAction(nameof(this.AuctionByUser));
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (!this.auctionService.OwnedByUser(userId, id))
            {
                return this.Unauthorized();
            }

            var input = this.auctionService.GetById<EditAuctionInputModel>(id);
            input.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

            return this.View(input);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, EditAuctionInputModel auction)
        {
            if (!this.ModelState.IsValid)
            {
                auction.CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs();

                return this.View(auction);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (!this.auctionService.OwnedByUser(userId, id))
            {
                return this.Unauthorized();
            }

            await this.auctionService.UpdateAsync(id, auction);

            this.TempData["Message"] = "The auction was successfully updated.";

            return this.RedirectToAction(nameof(this.SingleAuction), new { auctionId = id });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Delete(int auctionId)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (!this.auctionService.OwnedByUser(userId, auctionId))
            {
                return this.Unauthorized();
            }

            if (auctionId == 0)
            {
                return this.NotFound();
            }

            if (this.auctionService.IsThereLastBidder(auctionId))
            {
                return this.Unauthorized();
            }

            await this.auctionService.Delete(auctionId);

            this.TempData["Message"] = "The auction was successfully deleted.";

            return this.RedirectToAction(nameof(this.AuctionByUser));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> MoneyTransfer(int auctionId)
        {
            if (auctionId == 0)
            {
                return this.NotFound();
            }

            var auction = this.auctionService.GetById<SingleAuctionViewModel>(auctionId);
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var ownerId = auction.UserId;

            if (!this.auctionService.OwnedByUser(ownerId, auctionId))
            {
                return this.Unauthorized();
            }

            var amount = auction.CurrentPrice;

            var lastUser = this.userService.GetLastBidUser(auction.LastBidder);

            var history = this.historiesRepository.All()
                .FirstOrDefault(x => x.AuctionId == auction.Id && x.UserId == lastUser.Id);

            var virtualBids = history.BidAmount;

            await this.userService.GetFromUser(userId, amount, virtualBids);
            await this.userService.GetToOwner(ownerId, amount, auctionId);

            this.TempData["Message"] = "You have successfully paid";

            return this.RedirectToAction(nameof(this.UserPurchases));
        }

        [Authorize]
        public async Task<IActionResult> All(int category, int id = 1, int searchId = 1)
        {
            const int ItemsPerPage = 8;

            if (id <= 0)
            {
                return this.NotFound();
            }

            // TODO: think for categoryId check
            var auctionsCount = 0;
            var viewModel = new ListAuctionsViewModel();

            if (category == 0)
            {
                auctionsCount = this.auctionService.GetAuctionsCount();
                viewModel = new ListAuctionsViewModel
                {
                    CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs(),
                    ItemsPerPage = ItemsPerPage,
                    PageNumber = id,
                    Auctions = await this.auctionService.GetAllForSearch<ListAuctionViewModel>(category, id, ItemsPerPage),
                    Count = auctionsCount,
                };
            }
            else
            {
                auctionsCount = this.auctionService.GetAuctionsCountByCategory(category);
                viewModel = new ListAuctionsViewModel
                {
                    CategoriesItems = this.categoriesService.GetAllAsKeyValuePairs(),
                    ItemsPerPage = ItemsPerPage,
                    PageNumber = searchId,
                    Auctions = await this.auctionService.GetAllForSearch<ListAuctionViewModel>(category, searchId, ItemsPerPage),
                    Count = auctionsCount,
                };
            }

            //foreach (var auction in viewModel.Auctions)
            //{
            //    await this.auctionService.UpdateDbAuction(auction.Id);
            //}

            if (category != 0)
            {
                this.ViewBag.CurrentCategory = category;
            }

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult AuctionByUser(int id = 1)
        {
            const int ItemsPerPage = 8;

            if (id <= 0)
            {
                return this.NotFound();
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var viewModel = new ListAuctionsViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                Auctions = this.auctionService.GetUserAuctions<ListAuctionViewModel>(userId, id, ItemsPerPage),
                Count = this.auctionService.GetUserAuctionsCount(userId),
            };

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult UserPurchases(int id = 1)
        {
            const int ItemsPerPage = 8;

            if (id <= 0)
            {
                return this.NotFound();
            }

            var userEmail = this.User.FindFirst(ClaimTypes.Email).Value;

            var viewModel = new ListAuctionsViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                Auctions = this.auctionService.GetAllUserPurchases<ListAuctionViewModel>(userEmail, id, ItemsPerPage),
                Count = this.auctionService.GetUserPurchasesCount(userEmail),
            };

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult UserSales(int id = 1)
        {
            const int ItemsPerPage = 8;

            if (id <= 0)
            {

Web/AuctionHouse.Web/Controllers/SearchController.cs
namespace AuctionHouse.Web.Controllers
{
    using System.Threading.Tasks;

    using AuctionHouse.Services.Data;
    using AuctionHouse.Web.ViewModels.Auctions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class SearchController : BaseController
    {
        private readonly IAuctionService auctionService;

        public SearchController(IAuctionService auctionService)
        {
            this.auctionService = auctionService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Search(int id = 1)
        {
            const int ItemsPerPage = 8;

            if (id <= 0)
            {
                return this.NotFound();
            }

            var viewModel = new ListAuctionsViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                Auctions = await this.auctionService.GetAll<ListAuctionViewModel>(id, ItemsPerPage),
                Count = this.auctionService.GetAuctionsCount(),
            };

            return this.View(viewModel);
        }

        [Authorize]
        public PartialViewResult SearchAuctions(string searchText, int id = 1)
        {
            const int ItemsPerPage = 8;

            var viewModel = new ListAuctionsViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                Auctions = this.auctionService.GetSearch<ListAuctionViewModel>(searchText, id, ItemsPerPage),
                Count = this.auctionService.GetAuctionsCount(),
            };

            this.ViewBag.SearchText = searchText;

            return this.PartialView("_GridView", viewModel);
        }
    }
}

Web/AuctionHouse.Web/Views/Shared/_AlertPartial.cshtml
<div class="col-md-12">
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
        </symbol>
    </svg>
    <div class="alert alert-success alert-dismissible fade show" role="alert" id="success-alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill" /></svg>
        @this.TempData["Message"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

Web/AuctionHouse.Web/Views/Shared/_AuctionsListPartial.cshtml
@model ListAuctionsViewModel

<div class="row offset-1">
    @foreach (var auction in this.Model.Auctions)
    {
        <div class="card media border-info col-md-4 mb-4 mr-4" style="width: 18rem;">
            <img class="card-img-top" src="@auction.ImageUrl" alt="This auction doesn`t have image" width="100" height="200">
            <div class="card-body">
                <h3 class="card-title">@auction.Name</h3>
                <p class="card-text">Category: @auction.CategoryName</p>
                <p class="card-text">
                    @if (auction.IsPending)
                    {
                        <span class="h4 text-warning">Pending</span>
                    }
                    else
                    {
                        if (auction.IsActive == true)
                        {
                            <span class="h4 text-success">Active</span>
                        }
                        else
                        {
                            <span class="h4 text-danger">Inactive</span>
                        }
                    }

                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><span class="font-weight-bold">Starting price: </span>$@auction.Price</li>
                <li class="list-group-item"><span class="font-weight-bold">Current price: </span>$@auction.CurrentPrice</li>
                <li class="list-group-item"><span class="font-weight-bold">Owner: </span>@auction.UserUserName</li>
            </ul>
            <div class="card-body">
                <a asp-action="SingleAuction" asp-route-auctionId="@auction.Id" class="btn btn-success viewBtn">View</a>
            </div>
        </div>
    }
</div>

Web/AuctionHouse.Web/Views/Shared/_AuctionsPendingListPartial.cshtml
@model ListAuctionsViewModel

<div class="row offset-1">
    @foreach (var auction in this.Model.Auctions)
    {
        <div class="card media border-info col-md-4 mb-4 mr-4" style="width: 18rem;">
            <img class="card-img-top" src="@auction.ImageUrl" alt="This auction doesn`t have image" width="100" height="200">
            <div class="card-body">
                <h3 class="card-title">@auction.Name</h3>
                <p class="card-text">Category: @auction.CategoryName</p>
                <p class="card-text">
                    @if (auction.IsPending)
                    {
                        <span class="h4 text-warning">Pending</span>
                    }
                    else
                    {
                        if (auction.IsActive == true)
                        {
                            <span class="h4 text-success">Active</span>
                        }
                        else
                        {
                            <span class="h4 text-danger">Inactive</span>
                        }
                    }

                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><span class="font-weight-bold">Starting price: </span>$@auction.Price</li>
                <li class="list-group-item"><span class="font-weight-bold">Current price: </span>$@auction.CurrentPrice</li>
                <li class="list-group-item"><span class="font-weight-bold">Owner: </span>@auction.UserUserName</li>
            </ul>
            <div class="card-body">
                <a asp-area="Administration" asp-action="ApproveAuction" asp-route-auctionId="@auction.Id" class="btn btn-success viewBtn">View</a>
            </div>
        </div>
    }
</div>

Web/AuctionHouse.Web/Views/Shared/_CarsListPartial.cshtml
@model ListAuctionsViewModel

<div class="row offset-1">
    @foreach (var auction in this.Model.Auctions)
    {
        <div class="card media border-info col-md-4 mb-4 mr-4" style="width: 18rem;">
            <img class="card-img-top" src="@auction.ImageUrl" alt="This auction doesn`t have image" width="100" height="200">
            <div class="card-body">
                <h3 class="card-title">@auction.Name</h3>
                <p class="card-text">Category: @auction.CategoryName</p>
                <p class="card-text">
                    @if (auction.IsActive == true)
                    {
                        <span class="h4 text-success">Active</span>
                    }
                    else
                    {
                        <span class="h4 text-danger">Inactive</span>
                    }
                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><span class="font-weight-bold">Starting price: </span>$@auction.Price</li>
                <li class="list-group-item"><span class="font-weight-bold">Current price: </span>$@auction.CurrentPrice</li>
                <li class="list-group-item"><span class="font-weight-bold">Owner: </span>@auction.UserUserName</li>
            </ul>
            <div class="card-body">
                <a asp-action="SingleAuction" asp-route-auctionId="@auction.Id" class="btn btn-success viewBtn">View</a>
            </div>
        </div>
    }
</div>

Web/AuctionHouse.Web/Views/Shared/_Layout.cshtml
@using AuctionHouse.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link href="~/css/superhero.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    @await this.RenderSectionAsync("Background", required: false)
</head>
<body>
    <header>
        <nav class="navbar nav-tabs navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <img src="~/logo.png" width="75" height="70" alt="logo" class="navbar-brand" />
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1 ml-4">
                        <li class="nav-item h5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item h5 ml-2">
                                <a class="nav-link text-white" asp-area="" asp-controller="Search" asp-action="Search">Search Auction</a>
                            </li>
                            <li class="nav-item h5 ml-2 mr-2">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auctions" asp-action="Create">Create Auction</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle h5" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Auctions</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Auctions" asp-action="AuctionByUser">My Auctions</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Auctions" asp-action="UserPurchases">My Purchases</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Auctions" asp-action="UserSales">My Sales</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Auctions" asp-action="All">All Auctions</a>
                                </div>
                            </li>
                        }
                        @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle h5" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Control</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Administration" asp-controller="Categories" asp-action="Index">Categories</a>
                                    <a class="dropdown-item" asp-area="Administration" asp-controller="Auctions" asp-action="Index">Auctions</a>
                                    <a class="dropdown-item" asp-area="Administration" asp-controller="User" asp-action="Index">Users</a>
                                </div>
                            </li>

                            <li class="nav-item h5 ml-2 mr-2">
                                <a class="nav-link text-white" asp-area="Administration" asp-controller="Auctions" asp-action="PendingAuctions">Approving</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="/js/signalr/dist/browser/signalr.min.js" type="text/javascript" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/AuctionHouse.Web/Views/Shared/_PagingCommentsPartial.cshtml
@model AuctionHouse.Web.ViewModels.PagingViewModel
@{
    var auctionId = this.ViewBag.AuctionId;
}

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-route-auctionId="@auctionId" asp-route-id="@Model.PreviousPageNumber">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-route-auctionId="@auctionId" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">@Model.PageNumber <span class="sr-only">(current)</span></a>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-route-auctionId="@auctionId" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-route-auctionId="@auctionId" asp-route-id="@Model.NextPageNumber">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

Web/AuctionHouse.Web/Views/Shared/_PagingPartial.cshtml
@model AuctionHouse.Web.ViewModels.PagingViewModel

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item @if (!Model.HasPreviousPage) { <text>disabled</text> }">
            <a class="page-link" asp-route-id="@Model.PreviousPageNumber">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for (int i = Model.PageNumber - 4; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">@Model.PageNumber <span class="sr-only">(current)</span></a>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 4; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-route-id="@i">@i</a></li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) { <text>disabled</text> }">
            <a class="page-link" asp-route-id="@Model.NextPageNumber">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>